package ballidaku.resuablecomponents.myRealm;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;

/**
 * Created by brst-pc93 on 4/24/17.
 */

public class User extends RealmObject
{
    private String name;
    private int age;

    @PrimaryKey
    private int id;

    // Standard getters & setters generated by your IDE…
    public String getName()
    {
        return name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public int getAge()
    {
        return age;
    }

    public void setAge(int age)
    {
        this.age = age;
    }

    public int getId()
    {
        return id;
    }

    public void setId(int id)
    {
        this.id = id;
    }
}
